### ISSUE TITLE
Where are your codes

### ISSUE THREAD

**Issue by hejunqing** [tianzhiliang/MemoryAugDialog#1]
Dear Zhiliang, I red your paper in acl 2019. I am very interested in your work and want to reproduce it. But I am a beginner of pytorch. Expecting your code!

**Comment by tianzhiliang** [comment]
Sure, I will update codes here in a few days~

**Comment by tianzhiliang** [comment]
> Dear Zhiliang, I red your paper in acl 2019. I am very interested in your work and want to reproduce it. But I am a beginner of pytorch. Expecting your code!

Sure, I will update codes here in a few days~

**Comment by wizare** [comment]
Dear Zhiliang, your work in acl 2019  is very inspired. I am also looking forward to your code!
