### ISSUE TITLE
Where is the datasets

### ISSUE THREAD

**Issue by carinazhang-meng** [tianzhiliang/MemoryAugDialog#3]
I found the weibo datasets in this url:https://ai.tencent.com/ailab/nlp/dialogue/, but I guess the data  changed maybe, I want to ask about the original dataset for the paper.

**Comment by tianzhiliang** [comment]
Our dataset is the same as "Weibo Conversation Datasets" mentioned in https://ai.tencent.com/ailab/nlp/dialogue/. Thanks!
